spring:
  application:
    name: bingsoochef
  profiles:
    include:
      - datasource
      - mail
      - security

springdoc:
  use-fqn: true

jackson:
  deserialization:
    FAIL_ON_NULL_FOR_PRIMITIVES: true